#ifndef FONTAWESOME_H
#define FONTAWESOME_H

#include <QString>
#include <QChar>
#include <QFont>
#include <QMap>

class FontAwesome
{
public:
    static FontAwesome &instance();

    enum Icon {
        IconNone = 0,
        IconFolderOpen,
        IconFloppyDisk,
        IconExport,
        IconUndo,
        IconRedo,
        IconZoomIn,
        IconZoomOut,
        IconCompress,
        IconSearch,
        IconCrop,
        IconPaintbrush,
        IconEraser,
        IconTint,
        IconFont,
        IconBold,
        IconItalic,
        IconTextHeight,
        IconAlignLeft,
        IconAlignCenter,
        IconAlignRight,
        IconList,
        IconImage,
        IconSliders,
        IconSun,
        IconMoon,
        IconAdjust,
        IconCog,
        IconWrench,
        IconHandPaper,
        IconCrosshairs,
        IconMousePointer,
        IconPlus,
        IconMinus,
        IconTimes,
        IconCheck,
        IconChevronLeft,
        IconChevronRight,
        IconChevronUp,
        IconChevronDown,
        IconArrowLeft,
        IconArrowRight,
        IconArrowUp,
        IconArrowDown,
        IconArrowsAlt,
        IconExpand,
        IconExpandAlt,
        IconRandom,
        IconSync,
        IconRefresh,
        IconLock,
        IconUnlock,
        IconCamera,
        IconVideo,
        IconMusic,
        IconFile,
        IconFolder,
        IconTrash,
        IconPencil,
        IconEdit,
        IconCopy,
        IconCut,
        IconPaste,
        IconSave,
        IconDownload,
        IconUpload,
        IconCloud,
        IconCloudDownload,
        IconCloudUpload,
        IconBolt,
        IconFire,
        IconMagic,
        IconObjectGroup,
        IconObjectUngroup,
        IconSpinner,
        IconCircle,
        IconSquare,
        IconDotCircle,
        IconPlay,
        IconPause,
        IconStop,
        IconStepForward,
        IconStepBackward,
        IconFastForward,
        IconFastBackward,
        IconArrowsH,
        IconArrowsV,
        IconGenderless,
        IconMars,
        IconVenus,
        IconTransgender,
        IconNeuter,
        IconMercury,
        IconNeuterAlt,
        IconGenderlessAlt,
        IconCircleNotch,
        IconCogAlt,
        IconHistory,
        IconHourglass,
        IconHourglassHalf,
        IconAnchor,
        IconGlobe,
        IconLink,
        IconPaperPlane,
        IconSend,
        IconMoneyBill,
        IconCreditCard,
        IconReddit,
        IconRedditSquare,
        IconTwitter,
        IconTwitterSquare,
        IconFacebook,
        IconFacebookSquare,
        IconGithub,
        IconGithubAlt,
        IconGithubSquare,
        IconInstagram,
        IconWhatsapp,
        IconTelegram,
        IconTelegramPlane,
        IconYoutube,
        IconYoutubePlay,
        IconYoutubeSquare,
        IconDiscord,
        IconSlack,
        IconSlackHash,
        IconSteam,
        IconSpotify,
        IconSoundcloud,
        IconSnapchat,
        IconSnapchatGhost,
        IconSnapchatSquare,
        IconPinterest,
        IconPinterestP,
        IconPinterestSquare,
        IconLinkedin,
        IconLinkedinIn,
        IconFirefox,
        IconChrome,
        IconSafari,
        IconEdge,
        IconInternetExplorer,
        IconWhatsappSquare,
        IconClone,
        IconQuestionCircle,
        IconInfoCircle,
        IconExclamationCircle,
        IconExclamationTriangle,
        IconTimesCircle,
        IconCheckCircle,
        IconBan,
        IconTrashAlt,
        IconCameraRetro,
        IconKey,
        IconCogs,
        IconComments,
        IconThumbsUp,
        IconThumbsDown,
        IconHeart,
        IconHeartAlt,
        IconStar,
        IconStarAlt,
        IconStarHalf,
        IconUser,
        IconUsers,
        IconFilm,
        IconHome,
        IconClock,
        IconRoad,
        IconBook,
        IconBookmark,
        IconTag,
        IconTags,
        IconCalendar,
        IconMap,
        IconMapMarkerAlt,
        IconBriefcase,
        IconBuilding,
        IconBank,
        IconUniversity,
        IconSmile,
        IconMeh,
        IconFrown,
        IconBahai,
        IconCertificate,
        IconGraduationCap,
        IconLaptop,
        IconLaptopCode,
        IconLaptopMedical,
        IconMobile,
        IconMobileAlt,
        IconMoneyCheck,
        IconMoneyCheckAlt,
        IconTablet,
        IconDesktop,
        IconTools,
        IconWandMagic,
        IconBrush,
        IconPalette,
        IconSprayCan,
        IconStamp,
    };

    QChar icon(Icon icon) const;
    void setFontFamily(const QString &family);
    QString fontFamily() const { return m_fontFamily; }

    QFont font(qreal size = 16) const;

private:
    FontAwesome();
    FontAwesome(const FontAwesome &) = delete;
    FontAwesome &operator=(const FontAwesome &) = delete;

    QString m_fontFamily = "Font Awesome 6 Free Solid";
    QMap<Icon, QChar> m_icons;
};

#endif