#include "fontawesome.h"
#include <QFontDatabase>

FontAwesome &FontAwesome::instance()
{
    static FontAwesome instance;
    return instance;
}

FontAwesome::FontAwesome()
{
    m_icons = {
        {IconFolderOpen, QChar(0xf07c)},
        {IconFloppyDisk, QChar(0xf0c7)},
        {IconExport, QChar(0xf093)},
        {IconUndo, QChar(0xf0e2)},
        {IconRedo, QChar(0xf01e)},
        {IconZoomIn, QChar(0xf00e)},
        {IconZoomOut, QChar(0xf010)},
        {IconCompress, QChar(0xf066)},
        {IconSearch, QChar(0xf002)},
        {IconCrop, QChar(0xf05d)},
        {IconPaintbrush, QChar(0xf553)},
        {IconEraser, QChar(0xf12d)},
        {IconTint, QChar(0xf043)},
        {IconFont, QChar(0xf031)},
        {IconBold, QChar(0xf032)},
        {IconItalic, QChar(0xf033)},
        {IconTextHeight, QChar(0xf034)},
        {IconAlignLeft, QChar(0xf036)},
        {IconAlignCenter, QChar(0xf037)},
        {IconAlignRight, QChar(0xf038)},
        {IconList, QChar(0xf03a)},
        {IconImage, QChar(0xf03e)},
        {IconSliders, QChar(0xf1de)},
        {IconSun, QChar(0xf185)},
        {IconMoon, QChar(0xf186)},
        {IconAdjust, QChar(0xf042)},
        {IconCog, QChar(0xf013)},
        {IconWrench, QChar(0xf0ad)},
        {IconHandPaper, QChar(0xf256)},
        {IconCrosshairs, QChar(0xf05b)},
        {IconMousePointer, QChar(0xf245)},
        {IconPlus, QChar(0xf067)},
        {IconMinus, QChar(0xf068)},
        {IconTimes, QChar(0xf00d)},
        {IconCheck, QChar(0xf00c)},
        {IconChevronLeft, QChar(0xf053)},
        {IconChevronRight, QChar(0xf054)},
        {IconChevronUp, QChar(0xf077)},
        {IconChevronDown, QChar(0xf078)},
        {IconArrowLeft, QChar(0xf060)},
        {IconArrowRight, QChar(0xf061)},
        {IconArrowUp, QChar(0xf062)},
        {IconArrowDown, QChar(0xf063)},
        {IconArrowsAlt, QChar(0xf0b2)},
        {IconExpand, QChar(0xf065)},
        {IconExpandAlt, QChar(0xf423)},
        {IconRandom, QChar(0xf074)},
        {IconSync, QChar(0xf021)},
        {IconRefresh, QChar(0xf2f1)},
        {IconLock, QChar(0xf023)},
        {IconUnlock, QChar(0xf09c)},
        {IconCamera, QChar(0xf030)},
        {IconVideo, QChar(0xf03d)},
        {IconMusic, QChar(0xf001)},
        {IconFile, QChar(0xf15b)},
        {IconFolder, QChar(0xf07b)},
        {IconTrash, QChar(0xf1f8)},
        {IconPencil, QChar(0xf303)},
        {IconEdit, QChar(0xf044)},
        {IconCopy, QChar(0xf0c5)},
        {IconCut, QChar(0xf0c4)},
        {IconPaste, QChar(0xf0ea)},
        {IconSave, QChar(0xf0c7)},
        {IconDownload, QChar(0xf019)},
        {IconUpload, QChar(0xf093)},
        {IconCloud, QChar(0xf0c8)},
        {IconCloudDownload, QChar(0xf381)},
        {IconCloudUpload, QChar(0xf382)},
        {IconBolt, QChar(0xf0e7)},
        {IconFire, QChar(0xf525)},
        {IconMagic, QChar(0xf6a1)},
        {IconObjectGroup, QChar(0xf247)},
        {IconObjectUngroup, QChar(0xf248)},
        {IconSpinner, QChar(0xf110)},
        {IconCircle, QChar(0xf111)},
        {IconSquare, QChar(0xf0c8)},
        {IconDotCircle, QChar(0xf192)},
        {IconPlay, QChar(0xf04b)},
        {IconPause, QChar(0xf04c)},
        {IconStop, QChar(0xf04d)},
        {IconStepForward, QChar(0xf050)},
        {IconStepBackward, QChar(0xf049)},
        {IconFastForward, QChar(0xf050)},
        {IconFastBackward, QChar(0xf049)},
        {IconArrowsH, QChar(0xf07e)},
        {IconArrowsV, QChar(0xf07d)},
        {IconGenderless, QChar(0xf22d)},
        {IconMars, QChar(0xf222)},
        {IconVenus, QChar(0xf221)},
        {IconTransgender, QChar(0xf224)},
        {IconNeuter, QChar(0xf22c)},
        {IconMercury, QChar(0xf223)},
        {IconNeuterAlt, QChar(0xf22c)},
        {IconGenderlessAlt, QChar(0xf22d)},
        {IconCircleNotch, QChar(0xf1ce)},
        {IconCogAlt, QChar(0xf085)},
        {IconHistory, QChar(0xf1da)},
        {IconHourglass, QChar(0xf254)},
        {IconHourglassHalf, QChar(0xf253)},
        {IconAnchor, QChar(0xf13d)},
        {IconGlobe, QChar(0xf0ac)},
        {IconLink, QChar(0xf0c1)},
        {IconPaperPlane, QChar(0xf1d8)},
        {IconSend, QChar(0xf1d9)},
        {IconMoneyBill, QChar(0xf0d6)},
        {IconCreditCard, QChar(0xf09d)},
        {IconReddit, QChar(0xf281)},
        {IconRedditSquare, QChar(0xf282)},
        {IconTwitter, QChar(0xf099)},
        {IconTwitterSquare, QChar(0xf081)},
        {IconFacebook, QChar(0xf082)},
        {IconFacebookSquare, QChar(0xf083)},
        {IconGithub, QChar(0xf09b)},
        {IconGithubAlt, QChar(0xf113)},
        {IconGithubSquare, QChar(0xf092)},
        {IconInstagram, QChar(0xf16d)},
        {IconWhatsapp, QChar(0xf232)},
        {IconTelegram, QChar(0xf2c6)},
        {IconTelegramPlane, QChar(0xf2c6)},
        {IconYoutube, QChar(0xf167)},
        {IconYoutubePlay, QChar(0xf167)},
        {IconYoutubeSquare, QChar(0xf431)},
        {IconDiscord, QChar(0xf392)},
        {IconSlack, QChar(0xf198)},
        {IconSlackHash, QChar(0xf198)},
        {IconSteam, QChar(0xf1b6)},
        {IconSpotify, QChar(0xf1bc)},
        {IconSoundcloud, QChar(0xf1be)},
        {IconSnapchat, QChar(0xf2ab)},
        {IconSnapchatGhost, QChar(0xf2ab)},
        {IconSnapchatSquare, QChar(0xf2ad)},
        {IconPinterest, QChar(0xf0d2)},
        {IconPinterestP, QChar(0xf231)},
        {IconPinterestSquare, QChar(0xf0d3)},
        {IconLinkedin, QChar(0xf08c)},
        {IconLinkedinIn, QChar(0xf0e1)},
        {IconFirefox, QChar(0xf269)},
        {IconChrome, QChar(0xf268)},
        {IconSafari, QChar(0xf083)},
        {IconEdge, QChar(0xf282)},
        {IconInternetExplorer, QChar(0xf26b)},
        {IconWhatsappSquare, QChar(0xf40c)},
        {IconClone, QChar(0xf24d)},
        {IconQuestionCircle, QChar(0xf059)},
        {IconInfoCircle, QChar(0xf05a)},
        {IconExclamationCircle, QChar(0xf06a)},
        {IconExclamationTriangle, QChar(0xf071)},
        {IconTimesCircle, QChar(0xf057)},
        {IconCheckCircle, QChar(0xf058)},
        {IconBan, QChar(0xf05e)},
        {IconTrashAlt, QChar(0xf1f8)},
        {IconCameraRetro, QChar(0xf083)},
        {IconKey, QChar(0xf084)},
        {IconCogs, QChar(0xf085)},
        {IconComments, QChar(0xf086)},
        {IconThumbsUp, QChar(0xf087)},
        {IconThumbsDown, QChar(0xf088)},
        {IconHeart, QChar(0xf004)},
        {IconHeartAlt, QChar(0xf004)},
        {IconStar, QChar(0xf005)},
        {IconStarAlt, QChar(0xf005)},
        {IconStarHalf, QChar(0xf089)},
        {IconUser, QChar(0xf007)},
        {IconUsers, QChar(0xf0c0)},
        {IconFilm, QChar(0xf008)},
        {IconHome, QChar(0xf015)},
        {IconClock, QChar(0xf017)},
        {IconRoad, QChar(0xf018)},
        {IconBook, QChar(0xf02d)},
        {IconBookmark, QChar(0xf02e)},
        {IconTag, QChar(0xf02b)},
        {IconTags, QChar(0xf02c)},
        {IconCalendar, QChar(0xf133)},
        {IconMap, QChar(0xf279)},
        {IconMapMarkerAlt, QChar(0xf3c5)},
        {IconBriefcase, QChar(0xf0b1)},
        {IconBuilding, QChar(0xf1ad)},
        {IconBank, QChar(0xf19c)},
        {IconUniversity, QChar(0xf19c)},
        {IconSmile, QChar(0xf118)},
        {IconMeh, QChar(0xf11a)},
        {IconFrown, QChar(0xf119)},
        {IconGenderlessAlt, QChar(0xf22d)},
        {IconBahai, QChar(0xf666)},
        {IconCertificate, QChar(0xf0a3)},
        {IconGraduationCap, QChar(0xf19d)},
        {IconLaptop, QChar(0xf109)},
        {IconLaptopCode, QChar(0xf5fc)},
        {IconLaptopMedical, QChar(0xf812)},
        {IconMobile, QChar(0xf10b)},
        {IconMobileAlt, QChar(0xf3cd)},
        {IconMoneyCheck, QChar(0xf53c)},
        {IconMoneyCheckAlt, QChar(0xf53d)},
        {IconTablet, QChar(0xf10a)},
        {IconDesktop, QChar(0xf108)},
        {IconTools, QChar(0xf7d9)},
        {IconWandMagic, QChar(0xf84a)},
        {IconBrush, QChar(0xf55f)},
        {IconPalette, QChar(0xf53f)},
        {IconSprayCan, QChar(0xf5bd)},
        {IconStamp, QChar(0xf5bf)},
    };
}

QChar FontAwesome::icon(Icon icon) const
{
    return m_icons.value(icon, QChar());
}

void FontAwesome::setFontFamily(const QString &family)
{
    m_fontFamily = family;
}

QFont FontAwesome::font(qreal size) const
{
    QFont f(m_fontFamily);
    f.setPixelSize(size);
    return f;
}